//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_REST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int id_cliente { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public Nullable<int> id_departamento { get; set; }
    
        public virtual departamento departamento { get; set; }
    }
}
